apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: idp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: spotify/backstage:latest
        ports:
        - containerPort: 7007
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_CONFIG_app_baseUrl
          value: "http://localhost:3000"
        - name: APP_CONFIG_backend_baseUrl
          value: "http://localhost:7007"
        - name: APP_CONFIG_backend_database_client
          value: "pg"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: postgres-password
        - name: GRAFANA_CLOUD_URL
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: grafana-cloud-url
        - name: GRAFANA_CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: backstage-secrets
              key: grafana-cloud-api-key
        volumeMounts:
        - name: app-config
          mountPath: /app/app-config.yaml
          subPath: app-config.yaml
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 7007
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 7007
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: app-config
        configMap:
          name: backstage-config