apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
  labels:
    app: backstage
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: idp
type: Opaque
data:
  # Replace these with your actual base64 encoded values
  postgres-user: YmFja3N0YWdl  # backstage
  postgres-password: c2VjdXJlUGFzcw==  # securePass
  github-token: ""  # Add your GitHub token here (base64 encoded)
  grafana-cloud-url: ""  # Add your Grafana Cloud URL here (base64 encoded)
  grafana-cloud-api-key: ""  # Add your Grafana Cloud API key here (base64 encoded)